### ISSUE TITLE
Change Color Of Lines?

### ISSUE THREAD

**Issue by Moon-developer** [Tastenkunst/brfv4_javascript_examples#48]
I found in the Smile_Detection example where the color changes but it's using bit-shift from the looks of it and I do not understand what is happening to change it from red/green to black/white. Any help on how to go about changing colors with a smooth transition between two values?

**Comment by MarcelKlammer** [comment]
A color has three channels: red, green, blue (RGB). 

A channel is a value between 0 and 256 (decimal system), or 0x00 to 0xFF (hexadecimal system)

So a RGB color is a hex number between 0x000000 (black) and 0xFFFFFF (white).

Other colors:
0xFF0000 (full red, green and blue channel are 0)
0x00FF00 (full green, red and blue channel are 0)

And any other combination of channel values.

So the code:

`
if(smileFactor < 0.0) { smileFactor = 0.0; }
if(smileFactor > 1.0) { smileFactor = 1.0; }

var color = (((0xff * (1.0 - smileFactor) & 0xff) << 16)) + (((0xff * smileFactor) & 0xff) << 8);
`
means: smileFactor == 1.0 -> show all green, smileFactor == 0.0 -> show all red.

red part: (((0xff * (1.0 - smileFactor) & 0xff) << 16))

256 * (1 - smileFactor) is 256, when smileFactor is 0 and it is 0 when smileFactor is 1.

& 0xff masks the number and clips it to full values of 0 to 256...
<< 16 shifts bits from a 0xff number to be a 0xff0000 number (<< 8 would produce 0xff00, which is done for the green part).

So to get a smooth black to white transition you just need to calculate one channel, because for black, white and all pure gray tones, all channels are the same value.

`
var channel = (0xff * smileFactor) & 0xff;
var color = (channel << 16) + (channel << 8) + channel;
`

That should be it.

**Comment by Moon-developer** [comment]
Thank you so much. That helped a lot! Need to read up more on shifting bits for these purposes. Gonna play around till I get the colors I like. Thank you again.
