### ISSUE TITLE
Doesn't work on iOS 11 yet?

### ISSUE THREAD

**Issue by mrgoonie** [Tastenkunst/brfv4_javascript_examples#9]
It seems doesn't work on Safari iOS 11, does it?

**Comment by MarcelKlammer** [comment]
It works kind of. On iPad Pro without any additional rendering going on (like ThreeJS or PNG overlay) it works with 30 FPS, so quite awesome. On iPhone 6 it doesn't really start, I thin they still have that bug, that getUserMedia needs to be started after a user input... not sure... Need to look into that at some point.

**Comment by mrgoonie** [comment]
Yea, all I can see on my iPhone 6s+ is a black canvas after pressing allow the camera permission popup

**Comment by csalmeida** [comment]
Rendering the grid upon face detection worked for me on Safari iOS. 
I did a few things in order to work:
- Add `https` to development as it's a requirement of WebRTC.
- Disabled _Prevent Cross-Site Tracking_ on Safari iOS settings.
- Sometimes the camera freezes after allowing it on Safari iOS. As a work around, I've toggled the camera by pressing the red camera icon.
> Tested on iPhone 7

Not sure how to make it more stable though.
Great SDK!

**Comment by MarcelKlammer** [comment]
I tried it myself and was able to export a WebAssembly version which runs more smoothly. I also implemented a workaround for the freezing camera on iOS and the startup "bug" in iPhones:

https://tastenkunst.s3.amazonaws.com/demos/brfv4/test/index.html

It's not on Github yet. Will add that in the coming week or so.

**Comment by csalmeida** [comment]
Looking good, well done @MarcelKlammer! 🏅 

I've tested this on a few devices:
* Google Chrome 61 on MacOS High Sierra 10.13 **✓**
* Firefox Developer Edition 57.0b9 on MacOS High Sierra 10.13 **✓**
* Firefox 56.0.1 on MacOS High Sierra 10.13 **✓**
_Ignores css filter._
* Safari 11.0 on MacOS High Sierra 10.13 **✓**
* Safari 11.0 on iOS 11 - iPhone 7 **✓**
* Firefox 9.2 on iOS 11 - iPhone 7 **X** 
_No access to navigatior.getUserMedia._
* Google Chrome 62 on iOS 11 - iPhone 7 **X** 
_No access to navigatior.getUserMedia._
* Safari iOS on iOS 10 - iPad **X**
_No access to navigatior.getUserMedia._
* Safari iOS on iOS 10 - iPhone 6 **X**
_No access to navigatior.getUserMedia._
* Safari iOS on iOS 11 - iPhone 6 Plus **✓**
_No errors, sometimes a black screen instead of camera stream._
* Google Chrome 60 on Android 7.0 Nougat - Motorola G4 **✓**
_Low frame rate._
* Google Chrome 60 on Android 7.0 Nougat - Nexus 6 **✓**
_Low frame rate._
* Firefox 56 on Android 7.0 Nougat - Nexus 6 **✓**
_Low frame rate.
Ignores css filter._

**Comment by MarcelKlammer** [comment]
Thanks for testing Cristiano. All of this is to be expected IMHO.
